import { Post, Product } from '../types';

export const samplePosts: Post[] = [
  {
    _id: '1',
    title: 'Introduction to MERN Stack',
    slug: 'introduction-to-mern-stack',
    content: '<p>The MERN stack is a popular JavaScript stack used for easier and faster deployment of full-stack web applications. MERN comprises MongoDB, Express, React, and Node.js.</p><p>It is designed to make the development process smoother and easier.</p>',
    imageUrl: 'https://picsum.photos/800/400?random=1',
    author: 'Admin',
    metaTitle: 'Introduction to MERN Stack - Full Guide',
    metaDescription: 'Learn what MERN stack is and why it is popular for web development.',
    keywords: ['mern', 'javascript', 'fullstack'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '2',
    title: 'SEO Best Practices for React',
    slug: 'seo-best-practices-for-react',
    content: '<p>Search Engine Optimization (SEO) in Single Page Applications (SPAs) like React can be challenging. However, with tools like React Helmet and Server Side Rendering (SSR), it becomes manageable.</p>',
    imageUrl: 'https://picsum.photos/800/400?random=2',
    author: 'SEO Expert',
    metaTitle: 'React SEO Guide',
    metaDescription: 'How to optimize your React application for search engines.',
    keywords: ['react', 'seo', 'spa'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const products: Product[] = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: 'https://picsum.photos/400/400?random=101',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 13 Pro 256GB Memory',
    image: 'https://picsum.photos/400/400?random=102',
    description:
      'Introducing the iPhone 13 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: 'https://picsum.photos/400/400?random=103',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: 'https://picsum.photos/400/400?random=104',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: 'https://picsum.photos/400/400?random=105',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: 'https://picsum.photos/400/400?random=106',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];